[package]
name = "cfx-storage2"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
auto_impl = "1.2"
kvdb-rocksdb = "0.19"
kvdb = "0.13"
parking_lot = "0.12"

ethereum-types = "0.12"

slab = "0.4.9"

[dev-dependencies]
rand = "0.8.0"
rand_distr = "0.4.0"
rand_chacha = "0.2.1"