[package]
name = "cfx-storage2-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

arbitrary = { version = "1", features = ["derive"] }

[dependencies.cfx-storage2]
path = ".."

[[bin]]
name = "fuzz_bitmap_constructors"
path = "fuzz_targets/fuzz_bitmap_constructors.rs"
test = false
doc = false
bench = false
